basePath: /api/v1/
definitions:
  domain.AcademicInfo:
    properties:
      admission_date:
        type: string
      class_section:
        type: string
      emergency_contact:
        type: string
      grade:
        type: string
      prev_school:
        type: string
      student_id:
        type: string
    required:
    - admission_date
    - class_section
    - emergency_contact
    - grade
    type: object
  domain.AuthToken:
    properties:
      access_token:
        type: string
      refresh_token:
        type: string
    type: object
  domain.EmploymentDetail:
    properties:
      conrtact_end_date:
        type: string
      employment_type:
        type: string
      joing_date:
        type: string
      salary:
        type: integer
    type: object
  domain.LoginRequest:
    properties:
      password:
        type: string
      username:
        type: string
    required:
    - username
    type: object
  domain.LoginRes:
    properties:
      data:
        $ref: '#/definitions/domain.AuthToken'
      message:
        type: string
      status:
        type: integer
    type: object
  domain.Meta:
    properties:
      current_page:
        type: integer
      per_page:
        type: integer
      total:
        type: integer
    type: object
  domain.PersonalInfo:
    properties:
      blood_group:
        type: string
      city:
        type: string
      date_of_birth:
        type: string
      email:
        type: string
      first_name:
        type: string
      ggnder:
        type: string
      last_name:
        type: string
      phone:
        type: string
      street_address:
        type: string
    required:
    - blood_group
    - city
    - date_of_birth
    - first_name
    - ggnder
    - last_name
    - phone
    - street_address
    type: object
  domain.PersonalInformation:
    properties:
      city:
        type: string
      date_of_birth:
        type: string
      email:
        type: string
      first_name:
        type: string
      gender:
        type: string
      last_name:
        type: string
      phone:
        type: string
      street_address:
        type: string
    required:
    - city
    - date_of_birth
    - first_name
    - gender
    - last_name
    - phone
    - street_address
    type: object
  domain.ProfessionalInformation:
    properties:
      department_id:
        type: integer
      experience:
        type: integer
      graduation_year:
        type: integer
      qualification:
        type: string
      subject_ids:
        items:
          type: integer
        type: array
      teacher_id:
        type: string
      uni_or_ins_name:
        type: string
    required:
    - department_id
    - qualification
    - subject_ids
    - teacher_id
    type: object
  domain.Student:
    properties:
      academic_info:
        $ref: '#/definitions/domain.AcademicInfo'
      created_at:
        type: string
      id:
        type: integer
      personal_info:
        $ref: '#/definitions/domain.PersonalInfo'
      updated_at:
        type: string
    required:
    - academic_info
    - personal_info
    type: object
  domain.StudentCreatePayload:
    properties:
      academic_info:
        $ref: '#/definitions/domain.AcademicInfo'
      created_at:
        type: string
      id:
        type: integer
      personal_info:
        $ref: '#/definitions/domain.PersonalInfo'
      updated_at:
        type: string
    required:
    - academic_info
    - personal_info
    type: object
  domain.StudentListRes:
    properties:
      data:
        items:
          $ref: '#/definitions/domain.Student'
        type: array
      message:
        type: string
      meta:
        $ref: '#/definitions/domain.Meta'
      status:
        type: integer
    type: object
  domain.StudentSuccessRes:
    properties:
      data:
        $ref: '#/definitions/domain.Student'
      message:
        type: string
      status:
        type: integer
    type: object
  domain.StudentUpdatePayload:
    properties:
      academic_info:
        $ref: '#/definitions/domain.AcademicInfo'
      created_at:
        type: string
      id:
        type: integer
      personal_info:
        $ref: '#/definitions/domain.PersonalInfo'
      updated_at:
        type: string
    required:
    - academic_info
    - personal_info
    type: object
  domain.SuccessRes:
    properties:
      message:
        type: string
      status:
        type: integer
    type: object
  domain.Teacher:
    properties:
      created_at:
        type: string
      employment_detail:
        $ref: '#/definitions/domain.EmploymentDetail'
      id:
        type: integer
      personal_info:
        $ref: '#/definitions/domain.PersonalInformation'
      professional_info:
        $ref: '#/definitions/domain.ProfessionalInformation'
      updated_at:
        type: string
    required:
    - employment_detail
    - personal_info
    - professional_info
    type: object
  domain.TeacherCreatePayload:
    properties:
      created_at:
        type: string
      employment_detail:
        $ref: '#/definitions/domain.EmploymentDetail'
      id:
        type: integer
      personal_info:
        $ref: '#/definitions/domain.PersonalInformation'
      professional_info:
        $ref: '#/definitions/domain.ProfessionalInformation'
      updated_at:
        type: string
    required:
    - employment_detail
    - personal_info
    - professional_info
    type: object
  domain.TeacherListRes:
    properties:
      data:
        items:
          $ref: '#/definitions/domain.Teacher'
        type: array
      message:
        type: string
      meta:
        $ref: '#/definitions/domain.Meta'
      status:
        type: integer
    type: object
  domain.TeacherSuccessRes:
    properties:
      data:
        $ref: '#/definitions/domain.Teacher'
      message:
        type: string
      status:
        type: integer
    type: object
  domain.TeacherUpdatePayload:
    properties:
      created_at:
        type: string
      employment_detail:
        $ref: '#/definitions/domain.EmploymentDetail'
      id:
        type: integer
      personal_info:
        $ref: '#/definitions/domain.PersonalInformation'
      professional_info:
        $ref: '#/definitions/domain.ProfessionalInformation'
      updated_at:
        type: string
    required:
    - employment_detail
    - personal_info
    - professional_info
    type: object
host: localhost:8080
info:
  contact: {}
  description: A comprehensive API for school management system.
  license:
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  title: School Management System API
  version: "1.0"
paths:
  /auth/login:
    post:
      consumes:
      - application/json
      description: Login in to account
      parameters:
      - description: User credentials
        in: body
        name: payload
        required: true
        schema:
          $ref: '#/definitions/domain.LoginRequest'
      produces:
      - application/json
      responses:
        "201":
          description: Logged in
          schema:
            $ref: '#/definitions/domain.LoginRes'
        "400":
          description: Bad Request
          schema: {}
        "500":
          description: Internal Server Error
          schema: {}
      summary: Login in to account
      tags:
      - Authentication
  /student/{student_id}:
    delete:
      consumes:
      - application/json
      description: Delete student
      parameters:
      - description: student_id
        in: path
        name: student_id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "201":
          description: student
          schema:
            $ref: '#/definitions/domain.SuccessRes'
        "400":
          description: Bad Request
          schema: {}
        "500":
          description: Internal Server Error
          schema: {}
      security:
      - JWT: []
      summary: Delete student
      tags:
      - Student
    get:
      consumes:
      - application/json
      description: Get student by id
      parameters:
      - description: student_id
        in: path
        name: student_id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "201":
          description: student
          schema:
            $ref: '#/definitions/domain.StudentSuccessRes'
        "400":
          description: Bad Request
          schema: {}
        "500":
          description: Internal Server Error
          schema: {}
      security:
      - JWT: []
      summary: Get student by id student
      tags:
      - Student
  /student/create:
    post:
      consumes:
      - application/json
      description: Create student
      parameters:
      - description: student
        in: body
        name: payload
        required: true
        schema:
          $ref: '#/definitions/domain.StudentCreatePayload'
      produces:
      - application/json
      responses:
        "201":
          description: Created new student
          schema:
            $ref: '#/definitions/domain.StudentSuccessRes'
        "400":
          description: Bad Request
          schema: {}
        "500":
          description: Internal Server Error
          schema: {}
      security:
      - JWT: []
      summary: Create student
      tags:
      - Student
  /student/list:
    get:
      consumes:
      - application/json
      description: Get student list
      produces:
      - application/json
      responses:
        "201":
          description: student
          schema:
            $ref: '#/definitions/domain.StudentListRes'
        "400":
          description: Bad Request
          schema: {}
        "500":
          description: Internal Server Error
          schema: {}
      security:
      - JWT: []
      summary: Get student list student
      tags:
      - Student
  /student/update:
    put:
      consumes:
      - application/json
      description: Update student
      parameters:
      - description: student
        in: body
        name: payload
        required: true
        schema:
          $ref: '#/definitions/domain.StudentUpdatePayload'
      produces:
      - application/json
      responses:
        "201":
          description: Updated student
          schema:
            $ref: '#/definitions/domain.StudentSuccessRes'
        "400":
          description: Bad Request
          schema: {}
        "500":
          description: Internal Server Error
          schema: {}
      security:
      - JWT: []
      summary: Update student
      tags:
      - Student
  /teacher/{teacher_id}:
    delete:
      consumes:
      - application/json
      description: Delete teacher
      parameters:
      - description: teacher_id
        in: path
        name: teacher_id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "201":
          description: teacher
          schema:
            $ref: '#/definitions/domain.SuccessRes'
        "400":
          description: Bad Request
          schema: {}
        "500":
          description: Internal Server Error
          schema: {}
      security:
      - JWT: []
      summary: Delete teacher
      tags:
      - Teacher
    get:
      consumes:
      - application/json
      description: Get teacher by id
      parameters:
      - description: teacher_id
        in: path
        name: teacher_id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "201":
          description: teacher
          schema:
            $ref: '#/definitions/domain.TeacherSuccessRes'
        "400":
          description: Bad Request
          schema: {}
        "500":
          description: Internal Server Error
          schema: {}
      security:
      - JWT: []
      summary: Get teacher by id teacher
      tags:
      - Teacher
  /teacher/create:
    post:
      consumes:
      - application/json
      description: Create teacher
      parameters:
      - description: teacher
        in: body
        name: payload
        required: true
        schema:
          $ref: '#/definitions/domain.TeacherCreatePayload'
      produces:
      - application/json
      responses:
        "201":
          description: Created new teacher
          schema:
            $ref: '#/definitions/domain.TeacherSuccessRes'
        "400":
          description: Bad Request
          schema: {}
        "500":
          description: Internal Server Error
          schema: {}
      security:
      - JWT: []
      summary: Create teacher
      tags:
      - Teacher
  /teacher/list:
    get:
      consumes:
      - application/json
      description: Get teacher list
      produces:
      - application/json
      responses:
        "201":
          description: teacher
          schema:
            $ref: '#/definitions/domain.TeacherListRes'
        "400":
          description: Bad Request
          schema: {}
        "500":
          description: Internal Server Error
          schema: {}
      security:
      - JWT: []
      summary: Get teacher list teacher
      tags:
      - Teacher
  /teacher/update:
    put:
      consumes:
      - application/json
      description: Update teacher
      parameters:
      - description: teacher
        in: body
        name: payload
        required: true
        schema:
          $ref: '#/definitions/domain.TeacherUpdatePayload'
      produces:
      - application/json
      responses:
        "201":
          description: Updated teacher
          schema:
            $ref: '#/definitions/domain.TeacherSuccessRes'
        "400":
          description: Bad Request
          schema: {}
        "500":
          description: Internal Server Error
          schema: {}
      security:
      - JWT: []
      summary: Update teacher
      tags:
      - Teacher
schemes:
- http
- https
securityDefinitions:
  JWT:
    description: JWT security accessToken. Please add it in the format "Bearer {AccessToken}"
      to authorize your requests.
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
